// On-demand visual/perf check for the Channels drawer windowing.
//
// Loads `sample-data/many-signals.mf4` (12k scalar channels, generated by
// `scripts/gen_many_signals_mf4.py` — NOT a committed fixture) through the
// real `openFiles` drop path, opens the Channels rail tab, and asserts the
// drawer mounts only a windowed slice of rows. Skips itself if the fixture
// is absent so it never breaks CI.

import { existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { test, expect } from "@playwright/test";

const thisDir = dirname(fileURLToPath(import.meta.url));
const MF4 = resolve(thisDir, "../../../sample-data/many-signals.mf4");

test.skip(
  !existsSync(MF4),
  "generate sample-data/many-signals.mf4 first (scripts/gen_many_signals_mf4.py)",
);

test("Channels drawer windows 12k MF4 signals", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto("/");
  await expect(page.getByTestId("worker-status")).toHaveText("workers ready");

  // Open the file via the same store action the drop handler uses, timing it.
  const openMs = await page.evaluate(async () => {
    const resp = await fetch("/sample-data/many-signals.mf4");
    const bytes = new Uint8Array(await resp.arrayBuffer());
    const t0 = performance.now();
    const r = await window.__drivelineDevHooks!.openFiles([
      { name: "many-signals.mf4", bytes },
    ]);
    const dt = performance.now() - t0;
    if (r.errors.length) throw new Error(JSON.stringify(r.errors));
    return dt;
  });
  console.log(`openFiles(12k channels): ${openMs.toFixed(0)} ms`);

  // Open the Channels rail tab and wait for the count pill to settle.
  const tOpen0 = Date.now();
  await page.getByTestId("rail-channels").click();
  const pill = page.getByTestId("channels-count-pill");
  await expect(pill).toHaveText("12000");
  await expect(page.getByTestId("channels-groups")).toBeVisible();
  console.log(`open Channels drawer -> rendered: ${Date.now() - tOpen0} ms`);

  // Windowing proof: only a small slice of the 12k rows is in the DOM.
  const mountedRows = await page
    .locator('[data-testid^="channel-row-"]')
    .count();
  console.log(`mounted channel rows: ${mountedRows} of 12000`);
  expect(mountedRows).toBeGreaterThan(0);
  expect(mountedRows).toBeLessThan(100);

  // Typing in the filter stays responsive — time a query + result settle.
  const tFilter0 = Date.now();
  await page.getByTestId("channels-search").fill("sig_01234");
  await expect(pill).toHaveText("1");
  console.log(`filter to 1 match: ${Date.now() - tFilter0} ms`);
  await page.getByTestId("channels-search").fill("");
  await expect(pill).toHaveText("12000");

  // Scroll deep into the list to exercise scroll-driven windowing, then
  // screenshot the full app and the drawer on its own.
  await page.getByTestId("channels-groups").evaluate((el) => {
    el.scrollTop = 150_000;
  });
  await page.waitForTimeout(100);
  await page.screenshot({ path: "tests/screenshots/many-signals-full.png" });
  await page
    .getByTestId("drawer-host")
    .screenshot({ path: "tests/screenshots/many-signals-drawer.png" });
});
