//! End-to-end check of the Format Agent path: decode the synthetic alien
//! `sample.acme` log with the recipe the agent derived for it
//! (`sample-data/sample.acme.recipe.json`), exercising the real `RecipeReader`.
//!
//! `sample.acme` is generated by `sample-data/generate_acme.py` and is
//! git-ignored, so this test skips itself when the binary is absent (the recipe
//! JSON is committed). Run `python3 sample-data/generate_acme.py` first.

use std::path::PathBuf;

use data_core::{FetchOpts, Reader, RecipeReader, SourceKind};

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/crates/data-core
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

#[test]
fn agent_recipe_decodes_sample_acme() {
    let root = repo_root();
    let acme = root.join("sample-data/sample.acme");
    let recipe_path = root.join("sample-data/sample.acme.recipe.json");

    let Ok(bytes) = std::fs::read(&acme) else {
        eprintln!(
            "skipping: {} not present (run generate_acme.py)",
            acme.display()
        );
        return;
    };
    let recipe_json =
        std::fs::read_to_string(&recipe_path).expect("committed golden recipe must exist");

    // 1. Dry run — the agent's `validate_recipe` signal — over the FULL file.
    let report = RecipeReader::dry_run(&bytes, &recipe_json, u32::MAX).unwrap();
    assert_eq!(report.records_decoded, 3000, "all records decode");
    assert_eq!(report.records_rejected, 0, "no framing violations");
    assert!(report.first_error.is_none());
    assert!(
        report.coverage > 0.999,
        "recipe consumes ~all bytes: {}",
        report.coverage
    );

    let ts = report.time_stats.expect("has time stats");
    assert_eq!(ts.monotonic_violations, 0, "timestamps are monotonic");
    // 100 Hz ⇒ 10 ms median spacing.
    assert_eq!(ts.median_delta_ns, 10_000_000);
    // 2024-01-01T00:00:00Z in ns.
    assert_eq!(ts.start_ns, 1_704_067_200_000_000_000);

    // Physically plausible per-channel ranges prove the field offsets/dtypes
    // and scales are right (the agent's whole job).
    let ch = |id: &str| {
        report
            .per_channel
            .iter()
            .find(|c| c.native_id == id)
            .unwrap()
    };
    let speed = ch("speed");
    assert!(
        speed.min >= 0.0 && speed.max <= 25.0,
        "speed {:?}",
        (speed.min, speed.max)
    );
    assert!(!speed.constant);
    let lat = ch("lat");
    assert!(
        (lat.min - 37.77).abs() < 0.1 && (lat.max - 37.78).abs() < 0.1,
        "lat {:?}",
        (lat.min, lat.max)
    );
    let lon = ch("lon");
    assert!(
        lon.min < -122.0 && lon.max < -122.0,
        "lon {:?}",
        (lon.min, lon.max)
    );
    let gear = ch("gear");
    assert!(
        gear.min >= 1.0 && gear.max <= 3.0,
        "gear {:?}",
        (gear.min, gear.max)
    );

    // 2. Open + fetch one channel's Arrow IPC, like a plot panel would.
    let reader = RecipeReader::open(&bytes, &recipe_json).unwrap();
    assert_eq!(reader.meta().kind, SourceKind::Recipe);
    assert_eq!(reader.meta().channels.len(), 8);
    let ipc = reader
        .fetch_range("speed", reader.meta().time_range, FetchOpts::default())
        .unwrap();
    assert!(!ipc.is_empty(), "produces Arrow IPC bytes");
}
