import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { decodeCalibration } from "./calibrationFromArrow";

// The committed fixture is generated by `arrow_calibration_ipc()` in
// `crates/data-core/src/fixtures.rs` (see the Rust contract test). It carries
// the single `CAM_FRONT` example camera from docs/13.
const fixturePath = resolve(
  __dirname,
  "../../../../test-fixtures/arrow_calibration.ipc",
);

describe("decodeCalibration (calibration Arrow IPC fixture)", () => {
  const bytes = readFileSync(fixturePath);

  it("decodes the single CAM_FRONT camera with exact values", () => {
    const res = decodeCalibration(new Uint8Array(bytes));
    expect(res.ok).toBe(true);
    if (!res.ok) return;

    expect(res.cameras).toHaveLength(1);
    const cam = res.cameras[0];

    expect(cam.name).toBe("CAM_FRONT");

    // Intrinsics: [fx, fy, cx, cy] + resolution [width, height]. The fixture
    // stores f32, so compare with a tolerance.
    expect(cam.intrinsics.fx).toBeCloseTo(1266.4, 1);
    expect(cam.intrinsics.fy).toBeCloseTo(1266.4, 1);
    expect(cam.intrinsics.cx).toBeCloseTo(816.3, 1);
    expect(cam.intrinsics.cy).toBeCloseTo(491.5, 1);
    expect(cam.intrinsics.width).toBe(1600);
    expect(cam.intrinsics.height).toBe(900);

    // Zero distortion (5 coefficients all zero).
    expect(cam.distortion).toHaveLength(5);
    for (const k of cam.distortion) expect(k).toBe(0);

    expect(cam.translation).toEqual([0, 0, 0]);

    // Scalar-last extrinsic quaternion from docs/13.
    expect(cam.quaternion).toEqual([-0.5, 0.5, -0.5, 0.5]);
    // Unit length.
    const [qx, qy, qz, qw] = cam.quaternion;
    expect(Math.hypot(qx, qy, qz, qw)).toBeCloseTo(1, 5);
  });

  it("is stable across repeated decodes (no input mutation)", () => {
    const a = decodeCalibration(new Uint8Array(bytes));
    const b = decodeCalibration(new Uint8Array(bytes));
    expect(a.ok && b.ok).toBe(true);
    if (a.ok && b.ok) {
      expect(a.cameras.length).toBe(b.cameras.length);
      expect(a.cameras[0].name).toBe(b.cameras[0].name);
    }
  });
});
